### ISSUE TITLE
setting a namespace errors without corresponding .ini file

### ISSUE THREAD

**Issue by mikemartin1090** [datfinesoul/aws-sso-roller#5]
According to the docs, I should be able to specify a namespace environment variable like so to prefix all of my profiles. Unfortunately, I'm getting an error if I do not have a corresponding .ini file:

```
➜  aws-sso-roller git:(main) SSO_START_URL='https://blah.awsapps.com/start' \                      [12:13:37]
  SSO_REGION='us-east-1' \
  NAMESPACE='blah' \
  ./aws-sso-roller.bash
:: client secret expires: 2022-07-27T23:45:27-0400

Please log in via SSO in your browser using the following URL:
https://device.sso.us-east-1.amazonaws.com/?user_code=BLAH-BLAH

Press [Enter] after you have logged in
:: Setting up roles for sandwich
::   SRE
./aws-sso-roller.bash: line 160: CUSTOM_DATA: unbound variable

:: Failure (status 1)
```

When I do have a `~/.aws_sso_roller/blah.ini` file with the below contents, your script works fine.
```
cli_pager=
region=us-east-1
```

**Comment by datfinesoul** [comment]
You are correct, this seems to happen if either the `.ini` file is missing, or empty.  I will put in a fix for this.

**Comment by datfinesoul** [comment]
Fixed in https://github.com/datfinesoul/aws-sso-roller/releases/tag/v1.1.1
